name: filesys scan
run-name: Trivy FS Scanning.

# trigger
on:
  push:
  workflow_dispatch:

jobs:
  trivyscan:
      name: Trivy FS Scan
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: table
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
