name: CI Workflow
run-name: ${{github.actor}} pushed changes.

# trigger
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
            -Dsonar.organization=verdant-sphere-sg
            -Dsonar.projectKey=Verdant-Sphere-SG_verdant-sphere-kv-app

  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  test:
    name: Test
    needs: [build]
    uses: ./.github/workflows/test.yaml
    with:
      version: "8.2"


   