name: Test Laravel App

# trigger
on:
  workflow_call:
   inputs:
      version:
        required: true
        type: string

jobs:
  test:
      name: Testing Laravel App
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:latest
          ports:
            - 3306:3306
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: false
              MYSQL_ROOT_PASSWORD: password
              MYSQL_USERNAME: root
              MYSQL_DATABASE: test

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare Action
          uses: ./.github/actions/prepare-action
          with:
            version: ${{ inputs.version }}

        - name: Restore the Cache
          id: cache
          uses: actions/cache@v3
          with:
            path: ./vendor
            key: ${{ github.sha }}-composer-

        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            composer install

        - name: Create .env
          run: |
            cp .env.ci .env
            cp .env.ci .env.testing
        
        - name: Generate the key
          run: |
            php artisan key:generate
        
        - name: Migrate the Database
          run: |
            php artisan migrate
        
        - name: Run Unit Testing
          run: |
            php artisan test
  
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v2.3.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
