name: Test Laravel App

# trigger
on:
  workflow_call:

jobs:
  test:
      name: Testing Laravel App
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:latest
          ports:
            - 3306:3306
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: false
              MYSQL_ROOT_PASSWORD: password
              MYSQL_USERNAME: root
              MYSQL_DATABASE: test

      steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: "8.2"

        - name: Checkout
          uses: actions/checkout@v4

        - name: Restore the Cache
          id: cache
          uses: actions/cache@v3
          with:
            path: ./vendor
            key: ${{ github.sha }}-composer-

        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            composer install

        - name: Create .env
          run: |
            cp .env.ci .env
            cp .env.ci .env.testing
        
        - name: Generate the key
          run: |
            php artisan key:generate
        
        - name: Migrate the Database
          run: |
            php artisan migrate
        
        - name: Run Unit Testing
          run: |
            php artisan test